#pragma once
#pragma comment(linker, "/EXPORT:DllMain=C:\\windows\\system32\\xinput1_4.dll.DllMain,@1")
#pragma comment(linker, "/EXPORT:XInputEnable=C:\\windows\\system32\\xinput1_4.dll.XInputEnable,@5")
#pragma comment(linker, "/EXPORT:XInputGetAudioDeviceIds=C:\\windows\\system32\\xinput1_4.dll.XInputGetAudioDeviceIds,@10")
#pragma comment(linker, "/EXPORT:XInputGetBatteryInformation=C:\\windows\\system32\\xinput1_4.dll.XInputGetBatteryInformation,@7")
#pragma comment(linker, "/EXPORT:XInputGetCapabilities=C:\\windows\\system32\\xinput1_4.dll.XInputGetCapabilities,@4")
#pragma comment(linker, "/EXPORT:XInputGetKeystroke=C:\\windows\\system32\\xinput1_4.dll.XInputGetKeystroke,@8")
#pragma comment(linker, "/EXPORT:XInputGetState=C:\\windows\\system32\\xinput1_4.dll.XInputGetState,@2")
#pragma comment(linker, "/EXPORT:XInputSetState=C:\\windows\\system32\\xinput1_4.dll.XInputSetState,@3")
#pragma comment(linker, "/EXPORT:func_100=C:\\windows\\system32\\xinput1_4.dll.#100,@100,NONAME")
#pragma comment(linker, "/EXPORT:func_101=C:\\windows\\system32\\xinput1_4.dll.#101,@101,NONAME")
#pragma comment(linker, "/EXPORT:func_102=C:\\windows\\system32\\xinput1_4.dll.#102,@102,NONAME")
#pragma comment(linker, "/EXPORT:func_103=C:\\windows\\system32\\xinput1_4.dll.#103,@103,NONAME")
#pragma comment(linker, "/EXPORT:func_104=C:\\windows\\system32\\xinput1_4.dll.#104,@104,NONAME")
#pragma comment(linker, "/EXPORT:func_108=C:\\windows\\system32\\xinput1_4.dll.#108,@108,NONAME")
